version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    depends_on:
      - db
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  frontend:
    container_name: foodgram-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    depends_on:
      - backend
      - frontend
    build:
      context: ../nginx/local
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - "80:80"
