version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    depends_on:
      - db
    restart: always
    image: primestr/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  frontend:
    container_name: foodgram-frontend
    depends_on:
      - backend
    image: primestr/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    depends_on:
      - frontend
    restart: always
    image: primestr/foodgram_nginx
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - "8500:80"
