# Generated by Django 3.2.3 on 2023-10-01 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230928_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно быть не менее 1 мин.'), django.core.validators.MaxValueValidator(1440, message='Время приготовления должно быть не более 1440 мин.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug должен содержать только буквы (строчные и заглавные), цифры, дефисы и подчеркивания.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug названия тега'),
        ),
    ]
