# Generated by Django 3.2.3 on 2023-10-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231001_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'default_related_name': 'ingredients_in_recipe', 'verbose_name': 'Состав рецепта', 'verbose_name_plural': 'Состав рецептов'},
        ),
    ]
