# Generated by Django 3.2.3 on 2023-10-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231004_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientInRecipe',
            new_name='RecipeEssentials',
        ),
    ]
